import type { SectionLibraryItem } from "./types";

export const SECTION_LIBRARY: SectionLibraryItem[] = [
  {
    id: "hero",
    type: "hero",
    title: "Hero",
    description: "Первый экран: заголовок, подзаголовок, CTA и изображение.",
    icon: "🧩",
    category: "Hero",
    defaultConfig: { slides: [] },
    supportedTemplates: ["any"],
  },
  {
    id: "promo",
    type: "promo",
    title: "Promo",
    description: "Промо-блоки, акции, баннеры с изображениями.",
    icon: "🏷️",
    category: "Marketing",
    defaultConfig: { blocks: [] },
    supportedTemplates: ["any"],
  },
  {
    id: "featuredProducts",
    type: "featuredProducts",
    title: "Featured Products",
    description: "Вывод избранных товаров (хиты) с лимитом.",
    icon: "⭐",
    category: "Commerce",
    defaultConfig: { title: "Хиты", limit: 8 },
    supportedTemplates: ["any"],
  },
  {
    id: "categories",
    type: "categories",
    title: "Categories",
    description: "Показывает категории магазина.",
    icon: "🗂️",
    category: "Commerce",
    defaultConfig: { title: "Категории", showCounts: true },
    supportedTemplates: ["any"],
  },
  {
    id: "reviews",
    type: "reviews",
    title: "Reviews",
    description: "Отзывы клиентов и рейтинг.",
    icon: "💬",
    category: "Social proof",
    defaultConfig: { title: "Отзывы", items: [] },
    supportedTemplates: ["any"],
  },
  {
    id: "faq",
    type: "faq",
    title: "FAQ",
    description: "Частые вопросы и ответы.",
    icon: "❓",
    category: "Utility",
    defaultConfig: { title: "FAQ", items: [] },
    supportedTemplates: ["any"],
  },
  {
    id: "countdown",
    type: "countdown",
    title: "Countdown",
    description: "Таймер до окончания акции.",
    icon: "⏳",
    category: "Marketing",
    defaultConfig: { title: "Акция", untilIso: "" },
    supportedTemplates: ["any"],
  },
  {
    id: "videoBanner",
    type: "videoBanner",
    title: "Video Banner",
    description: "Видео-баннер (URL только https + allowlist).",
    icon: "🎬",
    category: "Media",
    defaultConfig: { title: "", subtitle: "", videoUrl: "", posterUrl: null },
    supportedTemplates: ["any"],
  },
  {
    id: "storySlider",
    type: "storySlider",
    title: "Story Slider",
    description: "Сторис-лента с изображениями.",
    icon: "📱",
    category: "Media",
    defaultConfig: { title: "Stories", items: [] },
    supportedTemplates: ["any"],
  },
  {
    id: "footer",
    type: "footer",
    title: "Footer",
    description: "Контакты, ссылки, текст внизу.",
    icon: "🧾",
    category: "Footer",
    defaultConfig: { text: "", instagramUrl: "", phone: "" },
    supportedTemplates: ["any"],
  },
];

